### ISSUE TITLE
GUI on Main Menu

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#24]
The Windows 3.1 GUI in profile creation after hitting "New Game" seems a bit weird to be under the scan-line effect, instead of full bright.

The combo box's selection is full-bright.

**Comment by Maxwolf** [comment]
Yeah I need to change up those dialog to look like the main menu overlay so it matches. I will be doing this for the alpha, I just was lazy and didn't update or change them for the prototype since it was still functional.

Look and feel should be consistent across the entire main menu I will make it so!

**Comment by Maxwolf** [comment]
Removed the profile manager from the game, named the player character Vladimir Gagarin and the ship the player travels on Vostok 42.
