### ISSUE TITLE
Flow on Main Menu

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#25]
Feels a bit weird of having to click New Game twice.

Once to create a profile and select it, then to select an act.

If there is no profile, and a it's new game, once the user enters required information the game should just start.

**Comment by Maxwolf** [comment]
Ok so new game, I enter my profile information, save it, game will know you did this and then start a new game right away since it knows you only have act 1 unlocked. This way when players return to the main menu and click new game they will then be prompted by the chapter select menu which shows the acts they have unlocked so far in the story.

**Comment by Maxwolf** [comment]
Also worth noting it will only do this if the profile created is index 0, any other profiles that are added will not cause this behavior.

**Comment by kallman1206** [comment]
I see we had the same reaction to this @FoxCouncil. I initially thought it might be loading or something until nothing continued to (not?) happen.

**Comment by Maxwolf** [comment]
I think I am just going to remove the profile manager from the game. Since it's single player this won't really affect anything going forward.

**Comment by Maxwolf** [comment]
Removed the profile manager from the game, named the player character Vladimir Gagarin and the ship the player travels on Vostok 42.
