### ISSUE TITLE
Story Text Feature on Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#28]
The story text should let the user his space or other keys to continue dialog. 

Story text queues up to play, areas can force play dialog on top of waiting dialog's.

**Comment by Maxwolf** [comment]
I am not sure what key should be used to skip this dialog. Maybe if we told the player to hold down the enter/return key or something like that for a second to skip the dialog. Code wise it would preemptively end the current voice-over and let the queue in the manager that controls it transition to the next one right away.

**Comment by Maxwolf** [comment]
I am not sure what key should be used to skip this dialog. Maybe if we told the player to hold down the enter/return key or something like that for a second to skip the dialog. Code wise it would preemptively end the current voice-over and let the queue in the manager that controls it transition to the next one right away.

**Comment by Maxwolf** [comment]
Can close voice over with escape key but it doesn't shut them up, need to tie it to default sound channel.

**Comment by Maxwolf** [comment]
Voiceover popups now allow the user to press their escape key to stop any currently playing voiceover. This is the same key used to access the main menu which works in our favor since the popup is ontop of the game engine app and not action game window it actually would show up ontop of the menu which is bad. So to solve both problems pressing escape closes the voiceover if one is playing, pressing it again would bring up the main menu and the act of doing so would prevent the next voiceover from popping up until the menu was closed again which is a very nice closed loop I think and makes sense to the user.
