### ISSUE TITLE
Escape Key Doesn't Pause Game

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#29]
Seems like I ran out of water on my ship while in the escape menu when I was writing up some bugs.

**Comment by Maxwolf** [comment]
Since we was a multiplayer game for so long I never let the escape key actually pause the game. Now that we are doing a single-player game it would be no problem for me to make the simulation pause ticking when the main menu is shown.

I will also remove/change the text at the top of the main menu to actually say "Game is paused" instead of not paused like it does now.

**Comment by Maxwolf** [comment]
Game pauses now when main menu is active.
