### ISSUE TITLE
Teleporter on Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#31]
Once the announcer hits the last count, lock the user in place and do not allow the player to move.

This indicates a successful teleport action to the user.

**Comment by Maxwolf** [comment]
This is a great idea. Another one I wanted to do was make these big long tubes of glowing light that at like 500meters long that I could put the player at the top of and let gravity make them fall all the way down. When the teleporter triggers would be this crazy second of flying through the abyss until it faded out to level transition.

It would also have the added effect of not allowing the player to move since they will be in a freefall.

**Comment by kallman1206** [comment]
So there's a teleport dimension on the other side of the skybox in every map?

**Comment by Maxwolf** [comment]
It would not so much be a dimension as much as a piece of geometry outside the main level that I can spawn you at the top of. I would place like 3 of them so it looks like it goes on forever but when you touched the bottom it would put you right back at the top until the game triggered the map load.

**Comment by Maxwolf** [comment]
Closing this since #173 solves the problem of the player moving around on the teleporter pad. Now the mission briefing shows right away and any further key presses will fade out and load the level.
