### ISSUE TITLE
Act Transition on Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#32]
The player should only have his gun raised after the first shot is fired at the player.

Once the gun raises up the act text and transition can begin.

**Comment by Maxwolf** [comment]
I like this idea, that way the player is never the aggressor and the Americans always will be the ones that fired first. I will code it so during act 1 when you take damage the first time it will give and equip the weapon for the player and then transition the act to act 2. This whole thing will make it very dramatic like the act of being fired upon is what triggers the next act in the story.

**Comment by Maxwolf** [comment]
Created another class for Charon freight-master so he will give players their starting weapon and trigger the act 2 progression at that time. The reason for this is the timing is much nicer as it gives him a chance to say stop you are under arrest and shoot at the player making the Americans the aggressor in the story as they should be. Modified the guard entities to not use the DieLatency they required before so they would start shooting the player around the same time now they just die instance since the timing will be perfect.
