### ISSUE TITLE
Gunplay Pickups on Gameplay

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#36]
Picking up an empty gun with no ammo should not auto switch to that gun.

**Comment by Maxwolf** [comment]
I was thinking of putting some random amount of bullets in the weapons you pickup from the ground. It is underwhelming to encounter something like lightning gun and be unable to use it because you don't have even a single shot.

I think that if you pickup a gun from the ground it should at the very minimum have at least 1 shot left in it up to the total magazine capacity. I will add an option to the game that others have for "Auto-switch weapons" so players can turn that on or off depending on personal preferences. The default will be to switch to any weapon you picked up that has ammo in it.

**Comment by Maxwolf** [comment]
Fixed!
