### ISSUE TITLE
Fuel3 Too Dark

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#40]
Same issue as Charon Hypermarket

**Comment by Maxwolf** [comment]
Uglys fuel station is unfinished and yes, way to dark. The alpha will see his facility expanded and filled out to what I have in mind. The reason it was not filled out in prototype is because I was not sure if he should have a bar like atmosphere like Quarks, or something more like Stalker with old man in the bunker who wanted artifacts.

I think the end result will sort of a mix between them both as Ugly seems to fit that profile. Untrustworthy money hungry scumbag.

**Comment by Maxwolf** [comment]
Regenerated level and made it much larger, cleaning it up and redoing it entirely to make it a playable level in the game and not just a place that you visit.
