### ISSUE TITLE
Is the truck American?

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#44]
Miles?
vs
Kilometers?

**Comment by Maxwolf** [comment]
The truck is Russian. You are Russian. I could change it up to use kilometers but I figure most players are American so miles seemed to make more sense.

On the other hand maybe some Navy unit like nautical miles would make more sense in space, the only negative with that is that almost everybody has no idea how long a nautical mile is so the numbers would become meaningless.

**Comment by kallman1206** [comment]
I mean I'm pretty sure most folks operating in space use SI units, but kilometres don't mean much when you're travelling millions of them at a time.

**Comment by DarkGuardsman** [comment]
Units are not very important as long as they are given context. Like 10 of these gets you to the next objective.

**Comment by Maxwolf** [comment]
Very good point DarkCow good to see you! Yeah the units are not that important so long as the player knows there are X remaining until they reach target location from flight computer.

**Comment by Maxwolf** [comment]
Decided to stick with miles, since the Americans built the FTL drive we will assume the mathematics for it work out in miles and converting it to another unit just takes more time. Will be nice to even put some lore in computer console about this for players to read will make it feel more like a place where the ship is comprised of tech from several nations who all hate each other.
