### ISSUE TITLE
Amalthea

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#46]
Didn't know which 'mainframe' to hack

**Comment by Maxwolf** [comment]
Yeah I put like 6 of them in that back room. I think what I will do is make it so there is a door there which will not open until you hack a computer terminal or something like that to open it. Once it opens could have the mainframe just chilling there in the middle of the room for the player to target.

Another alternative approach would be to use a unique model that is different than the other computer mainframe props so the player knows beyond a shadow of a doubt that the computer they are looking for is "this one" because of the way it will be positioned in the room and looking different than others.

**Comment by Maxwolf** [comment]
Redid the room where that mainframe lives and added lighting to focus the players attention on that area. Should not be confusing anymore.

![image](https://cloud.githubusercontent.com/assets/6830398/16703541/6cd4ae88-4523-11e6-86ec-7ba334a6f2ad.png)
