### ISSUE TITLE
Going to Mars

### ISSUE THREAD

**Issue by FoxCouncil** [FoxBytes/SpaceTruckerBugs#47]
Stopped at Astroids1, could not go anywhere.

I had freedom emitter installed.

Left Jupiter while Lee Xin was talking.

**Comment by Maxwolf** [comment]
The flight computer uses keycards, acts, and previously visited locations to determine if you are allowed to goto a specific location or not depending on current act in the game. My guess is this bug is happening because I am checking something related to current act objective completed status and not being simple about it like "if act X then can go here"

Will simplify this system to prevent future problems with this going forward.

**Comment by Maxwolf** [comment]
Simplified the system for checking if you can goto a location, removed ability to stop at every location along the trail while moving at FTL speeds.

**Comment by Maxwolf** [comment]
Closing this since I fixed all the bugs related to checking for if you can goto a certain place during the main quest. The way it works now is acts have what locations the flight computer can target in them, so when you are on act 3 for example to goto Nix you can go back and fourth to Pluto and Fuel station 3 all you want but nothing else.

I thought this was a good balance between perception of freedom and keeping players on track.
