### ISSUE TITLE
Recommendations and comments

### ISSUE THREAD

**Issue by aob13** [FoxBytes/SpaceTruckerBugs#50]
There's a lot of confusing elements to the game while playing it. I am unable to differentiate between items and what I am supposed to do considering there's no pop up or notification on the missions received; only way to check is by going to tab, which is good to have a journal but need a notification.

When it comes to differentiation, there's elements that don't tell me what it is. For example, I am supposed to destroy the shield generator, how am I supposed to know what it looks like? I've run around the hypermarket and have seen these items:

1. http://i.imgur.com/M6RRXAt.png
2. http://i.imgur.com/Sy3liNW.jpg
3. http://i.imgur.com/TK3dBTU.jpg
4. http://i.imgur.com/yCn0uhk.png

I recommend something that indicates or is just really obvious that no one can mix it up. 

Weird things I've encountered so far:
1. I ran really fast up a stairwell and took damage.
2. I ran off the entrance stairwell and didn't take damage, so I went back up and jumped off again just to see if I would while not running and I did take damage that time.
3. Figured out what the generator was finally after shooting everything. 
4. No way of seeing health, ammo, armour.
5. Ran out of water while trying to find out how to use the ship (lol)
6. Wasn't able to select the teleporter screen for a while. Realised the frame around it to select it wasn't the same size as the actual computer screen.
7. If I get a weapon then get it again, it should count as ammo.
8. Game needs to pause when paused.
9. http://i.imgur.com/1eqaH37.png (The Specter?)

Other than that, going good so far. Will update when I get to another stage

**Comment by Maxwolf** [comment]
This is some really good feedback thank you! I will be able to look into all of these issues for the alpha, some like the stairs acting weird and no indicators for health, ammo being things I will get to and have made some plans for already even.

**Comment by Maxwolf** [comment]
For the shield generators I believe a chevron/marker system will do us good as on screen indicators for what needs blowing up. Could do this for current objectives also.

**Comment by Maxwolf** [comment]
Finally, I think a tutorial level that explains the ship maybe. Could have some voice over talking to explain all the bits and pieces and how they work. Similar to the hazard course in half-life we could call ours driver training.

**Comment by Maxwolf** [comment]
Added chevron markers to the shield generators that show up after the story begins in act 2, during act 1 they don't show up in the supermarket to prevent the player from getting confused.

You can see the markers through the wall and they fade out slowly to a maximum distance of 128 meters. This means that on all 7 maps you can see as you progress through the level even through walls where you need to go towards in order to destroy it.

I think this will make it more obvious and easy for players to find what they are looking for, and also to know what they game wants them to destroy as it is pointing right at them.

![image](https://cloud.githubusercontent.com/assets/6830398/16710734/77a75948-45ee-11e6-9f0b-8c617b6215d9.png)

**Comment by Maxwolf** [comment]
I also made the player not take falling damage or damage from impulse, this stops the damage by running into stairs problem you encountered. You can still launch yourself into things, but overall things are getting better.

On another note I also redid the teleporter machine entirely the hitbox is no longer a problem.

Will be able to close this when I finally solve the stairs problem and make going up and down them seamless as walking in a straight line.

**Comment by Maxwolf** [comment]
Game also pauses no when you pause for your 8th issue. In the future make these separate issues so they are easier to track kind of annoying to keep coming back to the same issue and not being able to close it.

**Comment by Maxwolf** [comment]
Your 4th issue was also dealt with. We have a HUD now built out of nixie tubes to show health, stamina, bullets in gun, and bullets on you total for given weapon/

**Comment by Maxwolf** [comment]
Closing this since stairs are much better, redid the marker and current objective system on screen to be even simpler than it was before. Shield generators glow like tutorial consoles did before along with things like trash cans to let the player know they are capable of interacting with these things and or need to shoot/destroy them.
