### ISSUE TITLE
Prevent switching to empty weapons

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#57]
Weapons with no ammo should not be able to be held to improve gameplay

**Comment by Maxwolf** [comment]
Excellent idea, I was not sure how to deal with this but not being able to equip weapons that are empty is a brilliant idea.

**Comment by DarkGuardsman** [comment]
I assume you store your weapons in an array or list, just do a boolean on each weapon like isEmpty(). Then when the weapon switch code is called skip over that weapon and switch to the next one.

**Comment by Maxwolf** [comment]
Yup that is what I did. I check if it exists initially and have another check for if it exists and has ammo in the weapon or actual bullets on the person to put into it (since it could just be empty and need reloading). All of this combined makes for proper checks that prevent weapons with no ammo from being equipped via mouse wheel. Next is stopping auto-switch to empty weapons.
