### ISSUE TITLE
AI shoot threw corners/walls

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#59]
Seems the AIs will fire rounds threw corners of some rooms hitting the player

**Comment by Maxwolf** [comment]
I noticed this also. When spawning on Nix sometimes I will get shot through a freaking wall and I am not sure where it comes from. Will have to do more investigation into this. Perhaps there are some holes in the geometry which they are able to 'see' you through.

**Comment by DarkGuardsman** [comment]
Might be the ray trace code, check to make sure its distance check for colliders is not larger than the smallest wall width.

**Comment by Maxwolf** [comment]
With the redone spawning system enemies will never spawn or waste ticks in fight regions the player is not currently inhabiting. This stops the problem of being blasted through walls since the player is not there within the bounds of the area where the monster is and he will not seek the player then.
