### ISSUE TITLE
Teleporter console is strange to use

### ISSUE THREAD

**Issue by kallman1206** [FoxBytes/SpaceTruckerBugs#6]
The hit box is strange, can only interact with certain parts of the monitor and from certain angles (though I know you're aware of this one, just being thorough.)

**Comment by Maxwolf** [comment]
Yeah the hitbox is weird, needs to be worked on and fixed so it hits every time.

**Comment by Maxwolf** [comment]
I am actually going to re-do this machine to use the two monitors that are animated right now and do nothing. This will let me fill in that space properly and also not block the edge of the teleporter and or put a pipe there instead.

One of the big monitors can display the level layout so you can see what it looks like, and the other will display all the info and offer up the buttons to select from. Will put switches to control it and monitor power ontop of that white console below those monitors.

**Comment by Maxwolf** [comment]
Started work on this today.

**Comment by Maxwolf** [comment]
Got all of the new code working for the modified teleporter pad on the players ship. Now there are two monitors which are coded to act as one single unit. Will require some work on levels that used this object but I have an idea of what model to use for them already. Closing this because the keyboard is very easy to select and works like a charm.

![image](https://cloud.githubusercontent.com/assets/6830398/16649415/b926c834-43ed-11e6-8877-01823df95a48.png)
