### ISSUE TITLE
First level needs more of a guide

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#61]
I had to wonder around a bit to figure out what each thing in the ship did. Most users will not figure things out as quickly and will report confusion as bugs. So hand holding towards each objective may be required. Could use a ship board AI to tell the player where each thing is with the ruse that the player is hung over or a little out of it.

**Comment by Maxwolf** [comment]
You are 100% correct been having issues with players getting very confused and not sure what to do when the game starts. Because of this I am even thinking of making another act that is like an intro so I can take the time explain Ugly, the ship, and whole bunch of lore before we dump you on a mission in the middle of it.

Good idea by making it like the player is drunk or out of it :)

**Comment by DarkGuardsman** [comment]
Do something like the Half Life 1 suit training system. We can call it "Mandatory training for ship licensing" and even give an achievement called "Official"

**Comment by Maxwolf** [comment]
Rebuilt a new marker system and tutorial for the start of the game to highlight with shiny emissive texture where to press use key and big 2D screen overlays that blink to show where current objective is. Both of these systems combined make teaching the player a pretty straight forward process.
