### ISSUE TITLE
Gun accuracy 

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#62]
I know your going for doom style gameplay but the gun almost never hits the center of its area. Trying to shoot across a small room is difficult resulting in rushing towards targets. Adding an aim option could solve this which causes the player to remain stationary to fire.

**Comment by Maxwolf** [comment]
Weapons use a dispersion angle to calculate the dispersal of all the bullets a given weapon fires. So if I wanted to make one of them accurate I could make the first shot super accurate and every shot after that use the normal dispersion angle.

That way the first shot from a volly of them will be the most accurate. I don't want to add like an "aim down the sights" system since that has been done to death.

**Comment by DarkGuardsman** [comment]
a cool down on movement might work with the dispersion system. More stationary smaller the dispersion and delay in movement could reset the first shot system.

Also even though aiming is over done its almost expect out of shooters these days. Not say we have to do it but even I keep checking if I could aim by pressing random buttons.

**Comment by Maxwolf** [comment]
For example, instead of aiming down the sights I would rather have some sort of slow-down mechanic because that is cool and fun for the player in small bursts they can control. I was going to have something like that based on critical hits but abandoned the idea because there is no way to excuse the mechanic in game lore. Ex. the player doesn't have drugs or tech that lets him perceive time slower than his enemies.

I am coding up the gun logic that uses the dispersion angle to take the players stamina and linear velocity into account when determining if the weapon will have dispersion on it that time. So now if you are standing still and shooting guys your accuracy is very high and dispersion low, if you are moving and or have low stamina your accuracy is low and dispersion high.

The con to this is we still have bad AI so chicken shooting while standing still will let you keep getting headshots on them when I implement that hitbox.

**Comment by Maxwolf** [comment]
Below is an example of how the dispersion angle code works now that I have modified it. So far this seems to be working very well in gameplay tests here. If you want to have a clear shot you need to not be damaged (bloody screen not health wise), not have stamina below 100, camera shaking, or have any linear velocity.

`
            var rot = GetFireRotation(mode.typeMode);
            Radian dispersionAngle = mode.typeMode.DispersionAngle;

            // Determines if dispersion angle will be used in player bullet trajectory calculation.
            var clearShot = true;

            // Dispersion angle will vary if player is moving, and at random when holding still.
            var playerUnit = GetParentUnit() as PlayerCharacter;
            if (playerUnit != null)
            {
                // Damaged players that are healing aim badly.
                if (playerUnit.BloodSpattersRemaining > 0)
                    clearShot = false;

                // Out-of-breath or over-encumbered players aim badly.
                if (playerUnit.Stamina < playerUnit.Type.StaminaMaximum)
                    clearShot = false;

                // Players cameras who are shaking will aim badly.
                if (playerUnit.CameraShakePulseValue > 0)
                    clearShot = false;

                // Players whom are moving will aim badly.
                if (playerUnit.GetLinearVelocity().Length() > 0)
                    clearShot = false;

                // Check if dispersion angle is not zero and we don't have a clear shot.
                if (dispersionAngle != 0 && !clearShot)
                {
                    var random = World.Instance.Random;
                    var matrix = Mat3.FromRotateByX(random.NextFloat() * MathFunctions.PI * 2);
                    matrix *= Mat3.FromRotateByZ(random.NextFloat() * dispersionAngle);
                    rot *= matrix.ToQuat();
                }
            }
            else
            {
                // Normal dispersion angle calculations for other game characters and entities that shoot bullets.
                if (dispersionAngle != 0)
                {
                    var random = World.Instance.Random;
                    var matrix = Mat3.FromRotateByX(random.NextFloat() * MathFunctions.PI * 2);
                    matrix *= Mat3.FromRotateByZ(random.NextFloat() * dispersionAngle);
                    rot *= matrix.ToQuat();
                }
            }

            // Create the bullet in the game world.
            obj.Rotation = rot;
            obj.PostCreate();
`
