### ISSUE TITLE
Headshot critical 

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#63]
I notices critical hits were a thing but headshots didn't result in a critical every time. Adding this will increase the bonus from aiming and allow more skilled players to fill important.

**Comment by Maxwolf** [comment]
No problem, will make the headshot one actually rigged to a invisible
sphere on their head to eat bullets and detect headshots.

On Mon, Jul 4, 2016 at 10:55 AM, Robert WC Seifert <notifications@github.com
> wrote:

> I notices critical hits were a thing but headshots didn't result in a
> critical every time. Adding this will increase the bonus from aiming and
> allow more skilled players to fill important.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FoxBytes/SpaceTruckerBugs/issues/63>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AGg5Pps8hAaIAbNTcVg-Br2FLrfpqCIrks5qSUkUgaJpZM4JEj_c>
> .
>



-- 
Ron 'Maxwolf' McDowell

**Comment by Maxwolf** [comment]
Will code this up tonight, will require placing regions around enemy heads to wait for critical bullets from the player to strike them. Since every bullet the player fires has the potential to be a critical, I will code it so if bullets from player touch this region it will trigger a headshot no matter what.

I have also added a system to slow the game down very slightly when this happens and it feels very cool and could let the player chain multiple headshots together and keep time slowed down when it happens allowing them to semi control time by getting nice shots and chaining them together into a combo.

**Comment by DarkGuardsman** [comment]
As cool as the slow time thing is it may not fit very well. I will play test it a few times and post feed back :)

**Comment by Maxwolf** [comment]
After trying this I realized it is not a good idea (keep triggering it when you don't want it), I will remove headshot prompt and leave criticals.

**Comment by Maxwolf** [comment]
Done!

**Comment by DarkGuardsman** [comment]
Ya the biggest issue with triggering a slowdown effect is you may not want it at all. Games like killing floor have this problem and it can be disorientating. However, the ideas of powers ups could be useful in future versions. Especially if we get larger levels that have tons of enemies to power threw.

**Comment by Maxwolf** [comment]
I actually like that effect from killing floor and it's why I added it!

**Comment by DarkGuardsman** [comment]
I use to like it but after a while it felt weird... especially in multiplayer as it effects everyone.

**Comment by Maxwolf** [comment]
Yeah this is all single player no worries about other people~
