### ISSUE TITLE
New Game

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#66]
When creating a new game is asks to make a profile. After doing this it goes back to the main menu leaving the user confused. It should go strait into the game at this point because the player selected new game.

**Comment by Maxwolf** [comment]
Agree the flow of this is not right and will be corrected.

**Comment by Maxwolf** [comment]
Removed the profile manager from the game, named the player character Vladimir Gagarin and the ship the player travels on Vostok 42.

**Comment by DarkGuardsman** [comment]
Sounds good, if you implement multiplayer you can implement usernames in the settings menu or piggy back steam.

**Comment by Maxwolf** [comment]
Yeah I would piggy back the name from Steam directly. If we did multiplayer would do some sort of state sync where clients are bots on my end and we all are sendings signals back and fourth like a chat room basically to keep the world state. Whoever started the game would be the admin and his world state would be used as source to force others to match.

There was another networking system in there before that we were using but ended up abandoning it due to to many technical problems in it's implementation. It was a server authoritative implementation.
