### ISSUE TITLE
Bug -  Teleporter screen is hard to select

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#68]

**Comment by Maxwolf** [comment]
Yeah the physics capsule on it seems to be derpy compared to others, giving everybody a hard time gotta like look at it just the right way.

**Comment by Maxwolf** [comment]
Redoing the teleporter computer today, the hitbox will be a keyboard now on a flat surface similar to flight computer except the player will look down at keyboard to bring up the GUI for it to select the teleporter destination they would like. Pics to follow.

**Comment by Maxwolf** [comment]
Got all of the new code working for the modified teleporter pad on the players ship. Now there are two monitors which are coded to act as one single unit. Will require some work on levels that used this object but I have an idea of what model to use for them already. Closing this because the keyboard is very easy to select and works like a charm.

![image](https://cloud.githubusercontent.com/assets/6830398/16649415/b926c834-43ed-11e6-8877-01823df95a48.png)
