### ISSUE TITLE
Explosion size on shield generator

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#69]
Its too high, all though it doesn't damage the player much it leaves the impression that it does

**Comment by DarkGuardsman** [comment]
As a note in the nix station one of the shield generators blows up setting off explosive containers in the next room. The explosion is too large...

**Comment by Maxwolf** [comment]
I agree I noticed that also the shield generator would cause an explosion barrel in another room to go off. I will make the explosion radius much smaller and make it not shake your screen so violently.

**Comment by DarkGuardsman** [comment]
Might want to also consider more details/interesting models. The generator looks like a cube mostly...

**Comment by Maxwolf** [comment]
Yeah it's actually a CPU node from Incognito which was used in that story. I am not sure if I will keep them or not the actual shield generator part is stupid now that we don't have multiplayer. I mean stupid in the sense that after you complete a level you might not have destroyed all the generators and it ends up being anti-climatic having to go back and look for them (even with new markers I added to help find them).

The mixup with consoles + keycards now is nice and I could do something like place a teleporter at the start like we have now but also place one near the end of the level so the player could quickly leave once they have gone through a really long level. Others I would want this mechanic such as first level with Charon hypermarket it's fun fighting in the store part.

I was thinking of maybe creating a third way to stop the player which could be some sort of emergency forcefields which need to have nearby power nodes destroyed in order to remove it. This would perform the mechanic the shield generators do now.

**Comment by Maxwolf** [comment]
Vastly reduced the size and power of explosions from shield generators and explosion barrels, they also will not shake the players screen anymore. Instead of traveling 10 or 50 meters in the case of explosion barrel they are reduced to 3 and 5 meter damage radius. Reduced the damage from 50 to 10 and 5, made the fire influence it exerts instant rather than waiting 0.1 ticks. Added some extra effects to explosion barrel when they blow up and made them easier to blow up (10 HP instead of 50).
