### ISSUE TITLE
Issue with recording software

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#70]
Several times while using OBS to record the game the image on the recording software froze to a single frame. I tested this with xsplit and fraps having the same issue. Not sure what is up but the software thinks the game is no longer updating.

**Comment by Maxwolf** [comment]
That is weird, I think that is something on your rig because I used Fraps to record the videos I have on youtube. It worked just fine. Would check that drivers are all up to date.

That aside, when editing fraps videos in sony vegas they have proprietary codec sometimes have to convert to raw AVI or something to edit it and re-export to what you want. I have to do this somestimes because the fraps codec will just crash when being used in sony vegas but is fine for recording the game while playing.

**Comment by DarkGuardsman** [comment]
I did get an error when launching the game that could be related. Didn't get a good read on what the error was but I think it was graphics related. As well I have two monitors and am using an Ultra wide monitor as my primary.

**Comment by Maxwolf** [comment]
In the logs folder there might be exception caught there. If so paste it here for us to inspect :>

**Comment by DarkGuardsman** [comment]
[Game.txt](https://github.com/FoxBytes/SpaceTruckerBugs/files/348701/Game.txt)

**Comment by Maxwolf** [comment]
Info: OGRE: !!! Direct3D Device Lost!

Looks like something killed the rendering engines pointer. I will have to try that recording software and see if I get something similar.

On this note the other thing that can cause this is when you change from fullscreen to windowed mode game engine has to destroy and rebuild rendering engine hook.

**Comment by DarkGuardsman** [comment]
I didn't change the graphics setting but I did alt-tab several times while playing. As I was filling out bug reports as I went through the game.

**Comment by Maxwolf** [comment]
Yeah probably just crashed because C# wrapper around OGRE lost context entirely. The game does run in a window quite well on this note. New version also when window loses focus will pause the game, in addition to the escape menu.

**Comment by Maxwolf** [comment]
Closing because no issues here with Fraps or built in Windows 10 recording capabilities.
