### ISSUE TITLE
Door doesn't open in nix station level

### ISSUE THREAD

**Issue by DarkGuardsman** [FoxBytes/SpaceTruckerBugs#72]
Second level in the game, I managed to get back into the first console to unlock the doors. After entering into the next room full of guys threw the first unlocked door the next large door wouldn't open. Tried to get a screen shot to show which door but screen shots don't work & recording software failed.

**Comment by Maxwolf** [comment]
Screenshot button is F12 and it will save to AppData\Local\Space Trucker\Screenshots. Can just drag the pics into comment box here but you know that I think already.

I will leave this open and check out the doors. I have since mixed it up with keycards + computer consoles so it's not always computer, computer, computer. The mechanic is the same keycards just open colored doors but mix it up but still force the player to go into other rooms they normally would not.

**Comment by DarkGuardsman** [comment]
hmm, might want to add waypoints/task indicators on the screen to confirm that.

**Comment by Maxwolf** [comment]
Agree, will eventually show what cards you have on left side of screen or on the center bottom perhaps between the nixie tubes. Maybe could even put them into nixie tubes as floating icons that might be cute/cool.

**Comment by DarkGuardsman** [comment]
![screenshot001](https://cloud.githubusercontent.com/assets/1477330/16601116/bfbe0510-42d8-11e6-8806-15cd93689b49.png)

**Comment by Maxwolf** [comment]
Should be a terminal in room on left of there that lets you unlock it. I updated this door to use a keycard in latest builds.

**Comment by DarkGuardsman** [comment]
Yep, I know just found the screen shot I took :) for reference

**Comment by Maxwolf** [comment]
Closing this as the door does open, just was badly designed by yours truley in prototype. Should be much nicer in Alpha.
